---
resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: artifactory-repository
  type: artifactory
  check_every: 1m
  source:
    endpoint: http://172.17.13.59:8081/artifactory
    repository: "http://localhost:8081/artifactory/npm-repo-cache/"
    regex: "myapp-(?<version>.*).txt"
    username: admin
    password: venki@521

jobs:
- name: build-and-save-to-artifactory
  serial: true
  public: true
  plan:
  - task: build-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      outputs:
      - name: build
      run:
        path: sh
        args:
        - -exc
        - |
          export DATESTRING=$(date +"%Y%m%d")
          echo "This is my file" > ./build/myapp-$(date +"%Y%m%d%H%S").txt
          find .
  - put: artifactory-repository
    params: { file: ./build/myapp-*.txt }

- name: trigger-when-new-file-is-added-to-artifactory
  serial: true
  public: true
  plan:
  - get: artifactory-repository
    trigger: true
    passed:
      - build-and-save-to-artifactory
  - task: use-new-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: file-repository
      run:
        path: sh
        args:
        - -exc
        - |
          export DATESTRING=$(date +"%Y%m%d")
          ls -la file-repository
          cat ./file-repository/myapp*.txt