---
resource_types:
- name: artifactory 
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: myapp
  type: git
  source:
    uri: https://github.com/vc4017/myapp.git
    branch: master
- name: uaa-build
  type: artifactory
  source:
    endpoint: http://172.17.13.59:8081/artifactory
    repository: "/example-repo-local/myapp"
    username: admin
    password: venki@521
    skip_ssl_verification: true

jobs:
- name: build        
  plan:
  - get: myapp
    trigger: true
  - task: build
    config:
      platform: linux
      inputs:
      - name: myapp
      outputs:
      - name: uaa_war
      image_resource:
        type: docker-image
        source: { repository: venki521/dockerimage }
      run:
        path: sh
        args:
        - -exc
        - |
          export TERM=dumb
          cd myapp
          npm pack
          mv ./myapp-*.tgz ../uaa_war
  - put: uaa-build
    params:
      file: uaa_war/myapp-*.tgz
