---
groups:
- name: main
  jobs:
  - test
  - build-docker-image
  - build-artifact
  - deploy-job
resources:
- name: myapp
  type: git
  source:
    uri: https://github.com/vc4017/myapp.git
    branch: master

- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: vc4017@gmail.com
    password: Venki@521
    organization: vc4017-org
    space: deployment
    skip_cert_check: true

- name: docker-image
  type: docker-image
  source:
    email: tovenki.ch@gmail.com
    username: venki521
    password: venki@521
    repository: venki521/dockerimage

- name: artifactory
  type: artifactory
  source:
    endpoint: http://172.17.13.59:8081/artifactory
    repository: "example-repo-local/"
    regex: "pivotal-admin-(?<version>.*).tar.gz"
    username: admin
    password: venki@521

jobs:
 
- name: test
  serial: true
  disable_manual_trigger: false
  plan:
      - get: myapp
        trigger: true

      - task: npm-install
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: myapp
              path: .
          run:
            path: npm
            args: [ install ]

      - task: npm-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: myapp
              path: .
          run:
            path: npm
            args: [ install-test ]

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: myapp
    trigger: true
    passed:
       - test
  - put: docker-image
    params:
      build: myapp

- name: build-artifact
  public: true
  serial: true
  plan:
  - get: myapp
    trigger: true
    passed:
       - build-docker-image
  - put: artifactory
    params:
      build: myapp

- name: deploy-job
  serial: true
  plan:
  - get: myapp
    trigger: true
    passed:
      - build-docker-image
  - put: cf-env
    params:
      manifest: myapp/manifest.yml
      path: myapp