resource_types:
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: myapp
  type: git
  source:
    uri: https://github.com/vc4017/myapp.git
    branch: master
- name: uaa-build
  type: artifactory
  source:
    endpoint: http://172.17.13.59:8081/artifactory
    repository: "/example-repo-local/myapp"
    regex: "cloudfoundry-identity-uaa-(?.*).war"
    username: admin
    password: venki@521
    skip_ssl_verification: true

jobs:
  plan:
  - get: myapp
    trigger: true
  - task: build
    config:
      platform: linux
      inputs:
      - name: uaa_sources
      outputs:
      - name: uaa_war
      image_resource:
        type: docker-image
        source: { repository: venki521/dockerimage }
      run:
        path: sh
        args:
        - -exc
        - |
          export TERM=dumb
          cd uaa_sources
          ./gradlew :cloudfoundry-identity-uaa:war
          mv uaa/build/libs/cloudfoundry-identity-uaa-*.war ../uaa_war
  - put: uaa-build
    params:
      file: uaa_war/cloudfoundry-identity-uaa-*.war