---
resource_types:
  - name: cf-docker-resource
    type: docker-image
    source:
      repository: idahobean/cf-docker-resource

resources:
- name: cf-env
  type: cf-docker-resource
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

jobs:
- name: job-deploy-docker-image
  public: true
  serial: true
  plan:
  - put: cf-env
    params:
      repository: venki521/dockerimage
      current_app_name: my-app
      memory: 256M
      disk: 256M
      health_check: none