---
groups:
- name: main
  jobs:
  - generate node-modules and mocha test
  - build-docker-image and pushed to dockerhub
  - build-artifact and put artifact in jfrog artifactory
  - deploy to pws
 
resource_types:
- name: artifactory 
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource
 
resources:
- name: myapp
  type: git
  source:
    uri: {{git-uri}}
    branch: master

- name: cf-env
  type: cf
  source:
    api: {{pws-api}}
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-organization}}
    space: {{pws-space}}
    skip_cert_check: true

- name: docker-image
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-repo}}

- name: uaa-build
  type: artifactory
  source:
    endpoint: {{artifactory-endpoint}}
    repository: {{artifactory-repo}}
    regex: {{artifactory-regex}}
    username: {{artifactory-username}}
    password: {{artifactory-password}}
    skip_ssl_verification: true

jobs:
 
- name: generate node-modules and mocha test
  serial: true
  disable_manual_trigger: false
  plan:
      - get: myapp
        trigger: true
        
      - task: npm-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: myapp
              path: .
          run:
            path: npm
            args: [ install-test ]

- name: build-docker-image and pushed to dockerhub
  public: true
  serial: true
  plan:
  - get: myapp
    trigger: true
    passed:
      - generate node-modules and mocha test
  - put: docker-image
    params:
      build: myapp

- name: build-artifact and put artifact in jfrog artifactory     
  plan:
  - get: myapp
    trigger: true
    passed:
      - build-docker-image and pushed to dockerhub
  - task: build
    config:
      platform: linux
      inputs:
      - name: myapp
      outputs:
      - name: uaa_war
      image_resource:
        type: docker-image
        source: { repository: venki521/dockerimage }
      run:
        path: sh
        args:
        - -exc
        - |
          export TERM=dumb
          cd myapp
          npm pack
          mv ./hello-world-1.0.0.tgz ../uaa_war
  - put: uaa-build
    params:
      file: uaa_war/hello-world-*.tgz

- name: deploy to pws
  serial: true
  plan:
  - get: myapp
    trigger: true
    passed:
      - build-artifact and put artifact in jfrog artifactory
  - put: cf-env
    params:
      manifest: myapp/manifest.yml
      path: myapp

