---
groups:
- name: main
  jobs:
  - build-docker-image
  - deploy-job
resources:
- name: myapp
  type: git
  source:
    uri: https://github.com/vc4017/myapp.git
    branch: master

- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

- name: docker-image
  type: docker-image
  source:
    email: tovenki.ch@gmail.com
    username: venki521
    password: venki@521
    repository: venki521/dockerimage

jobs:

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: myapp
    trigger: true
  - put: docker-image
    params:
      build: myapp


- name: deploy-job
  serial: true
  plan:
  - {get: myapp, trigger: true}
  - put: cf-env
    params:
      manifest: myapp/manifest.yml
      path: myapp