---
resources:
- name: myapp
  type: git
  source:
    uri: https://github.com/vc4017/myapp.git
    branch: master

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: myapp
    trigger: true
  - task: run-unit-tests
    file: myapp/unit-tests.yml